### ISSUE TITLE
new project email doesn't contain the name of the project

### ISSUE THREAD

**Issue by kamfonik** [CCI-MOC/moc-openstack-tools#47]
We should include the name of the project to prevent confusion.

**Comment by morrme** [comment]
I see the new project email template .txt file. Do you need this file to be updated with the <PROJECT> field somewhere? 
Something like

`A new OpenStack project, <PROJECT>, has been created for you on MOC Production (Kaizen).`

Are there any other files that would be affected?

**Comment by kamfonik** [comment]
@morrme yes, that is the only change - there is actually a fix already in the open PR #48 that is waiting for review.  I goofed and put the wrong issue number there, so the tag didn't show up here until I corrected it just now.

The other place I needed to check to fix it was [here](https://github.com/CCI-MOC/moc-openstack-tools/blob/master/addusers.py#L126) to make sure the `project` keyword was being passed in to the Message constructor, but it was already there.

**Comment by morrme** [comment]
@kamfonik Oh, I'm sorry !

**Comment by kamfonik** [comment]
@morrme no worries, it wasn't obvious because of my mistake with the issue number.  Are you a new MOC person or just passing through looking for some projects?  Either way, welcome!

**Comment by morrme** [comment]
Just a new-to-github person hoping to contribute/learn in any way I can :) Thanks!

**Comment by kamfonik** [comment]
@morrme one of our other projects called HIL has some open issues marked as easy:
https://github.com/CCI-MOC/hil/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy

Feel free to take a look to see if anything there appeals to you!
