### ISSUE TITLE
HACKING.md suggests running a CentOS command on Ubuntu

### ISSUE THREAD

**Issue by greyspectrum** [CCI-MOC/moc-openstack-tools#76]
On line 61 of HACKING.md in the "documentation" branch, under "Install required packages," the documentation suggests running:

`$ sudo yum install python-virtualenv`

However, this part of the documentation covers setting up a Ubuntu VM, so I believe it should be:

`$ sudo apt install python-virtualenv`

**Comment by kamfonik** [comment]
@greyspectrum HACKING.md isn't actually in this repo yet, it's in a branch on my fork of it.

And Install Required Packages is actually a new heading, so we are back to assuming CentOS - although when I look at the formatted version it's not very obvious that that is the case, I will add some horizontal rules and fiddle with the heading levels to make that clearer.

**Comment by kamfonik** [comment]
@greyspectrum I am going to close this issue for now but the feedback is appreciated - feel free to either send me notes on slack or whatever, or just keep notes for yourself and comment when there is a PR.
